
- name: Elk setup
  hosts: elkserver
  user: root
  tasks:
    - name: copy the data
      copy:
        src: /var/lib/jenkins/workspace/elk-setup
        dest: $HOME/elk
    - name: bringing up the application
      command: chdir=/home/ubuntu/elk/docker docker-compose up -d
